[data]
vis = ""

[fields]
bpassfield = ""
fluxfield = ""
phasecalfield = ""
targetfields = ""
extrafields = ""

# See processMeerKAT.py -h for documentation
[slurm]
nodes = 1
ntasks_per_node = 8
plane = 1
mem = 232
partition = "Main"
exclude = ""
time = "12:00:00"
submit = false
container = "/idia/software/containers/casa-6.5.0-modular.sif"
mpi_wrapper = "mpirun"
name = ""
dependencies = ""
account = "b03-idia-ag"
reservation = ""
modules = ["openmpi/4.0.3"]
verbose = false
precal_scripts = [
  {script = "partition.py", mpi = true},
  {script = "partition_target.py", mpi = true},
]
postcal_scripts = [
  {script = "concat_caltables.py", mpi = false},
  {script = "apply_to_target.py", mpi = true},
  {script = "selfcal_part1.py", mpi = true},
  {script = "selfcal_part2.py", mpi = false},
  {script = "science_image.py", mpi = true},
]
scripts = [
  {script = "validate_input.py", mpi = false},
  {script = "flag_round_1.py", mpi = true},
  {script = "setjy.py", mpi = true},
  {script = "xx_yy_solve.py", mpi = false},
  {script = "xx_yy_apply.py", mpi = true},
  {script = "flag_round_2.py", mpi = true},
  {script = "xx_yy_solve.py", mpi = false},
  {script = "xx_yy_apply.py", mpi = true},
]
target_scripts = [
  {script = "validate_input.py", mpi = false},
  {script = "flag_round_1.py", mpi = true},
]

[crosscal]
minbaselines = 4
chanbin = 1
width = 1
timeavg = "8s"
createmms = true
keepmms = true
spw = "*:880~933MHz,*:960~1010MHz,*:1010~1060MHz,*:1060~1110MHz,*:1110~1163MHz,*:1299~1350MHz,*:1350~1400MHz,*:1400~1450MHz,*:1450~1500MHz,*:1500~1524MHz,*:1630~1680MHz"
nspw = 11
calcrefant = false
refant = "m059"
standard = "Stevens-Reynolds 2016"
badants = []
badfreqranges = ["933~960MHz", "1163~1299MHz", "1524~1630MHz"]

[selfcal]
nloops = 2
loop = 0
cell = "1.5arcsec"
robust = -0.5
imsize = [6144, 6144]
wprojplanes = 512
niter = [10000, 50000, 50000]
threshold = ["0.5mJy", 10, 10]
nterms = 2
gridder = "wproject"
deconvolver = "mtmfs"
calmode = ["", "p"]
solint = ["", "1min"]
uvrange = ""
flag = true
gaintype = "G"
discard_nloops = 0
outlier_threshold = 0.0
outlier_radius = 0.0

[image]
cell = "1.5arcsec"
robust = -0.5
imsize = [6144, 6144]
wprojplanes = 512
niter = 50000
threshold = 10
multiscale = [0, 5, 10, 15]
nterms = 2
gridder = "wproject"
deconvolver = "mtmfs"
restoringbeam = ""
stokes = "I"
pbthreshold = 0.1
pbband = "LBand"
mask = ""
rmsmap = ""
outlierfile = ""

[run]
continue = true
dopol = false
